### ISSUE TITLE
实测前两种docker方案失败，使用Dockerfile成功

### ISSUE THREAD

**Issue by lingr7** [BigLiao/markCV#2]
使用docker的方案中，前两种未生效。
os:windows10 20H2
env:wsl2-ubuntu20.04
docker：Docker Desktop 3.2.2
git clone之后，进入Dockerfile所在文件夹
```
docker build .
docker images
docker tag bf12c68a nodecv:0.1
docker run -v $(pwd):/markCV/app -p 3000:3000 -itd   --name mynode nodecv:0.1 bash
docker exec -it mynode bash
```
之后
```
npm run dev
```

**Comment by lingr7** [comment]
修正，应该是docker wsl2挂载文件目录有问题导致的。这三种本质上一样，只不过使用Dockerfile,最后使用的node版本是12.20.1

**Comment by BigLiao** [comment]
抱歉很久没维护。刚刚试了一下确实有问题，我这两天会修复一下。有使用建议欢迎提出
